[options]
list_db = True
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/oca-addons/manufacture,/mnt/oca-addons/helpdesk
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$wThHaI1xjtEa49zbOwfgHA$LZ0sTkaNdZnIf09r1kr9KWfnbn/QBXj9qEhHHmvJ.SGELErcqE7/2ulUakcFAp7mGhmjfUoqHfsmcwkvmOG86Q

